version: '3'
services:
  redis-server:
    image: 'redis'
  postgres-server:
    image: 'postgres:12'
    environment:
      - POSTGRES_DB=sports
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sports
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'postgres-server'
      - 'redis-server'
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:sports@postgres-server:5432/sports
      - PORT=8000
      - REDIS_URL=redis://redis-server:6379
      - WAIT_HOSTS=postgres-server:5432, redis-server:6379
